### ISSUE TITLE
[Enhancement] continue to development this project instead of lerna

### ISSUE THREAD

**Issue by nodece** [nicolo-ribaudo/yarn-plugin-babel-version#1]
I'm looking for a solution to release the my project on monorepo with independent versioning mode + yarn2 workspace environment, I found this project, and seems very suitable for my environment, but this project seems doesn't support the independent versioning mode and conventionalCommits, so I want to know if you are interested in continuing to develop, and many developers are looking for this solution. 

thank you for your time :)

**Comment by nicolo-ribaudo** [comment]
Hi @nodece!

Currently I don't have the bandwidth to maintain this project other than for what I need it for for Babel. I suggest cloning it and adapting it to your use case - if you need any help understanding some parts of the code, feel free to ask!

**Comment by nodece** [comment]
ok, thanks.
